version: "3"

services:
  #
  albion.guildbot:
    container_name: albion.guildbot
    image: aliart/albion.guildbot:1.0
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        DOCKER_UID: 1001
        DOCKER_GID: 1001
        USERNAME: guildbot
    networks:
      - albion.guildbot

networks:
  albion.guildbot:
    external:
      name: albion.guildbot
