version: "3"

services:
  #
  albion.guildbot:
    container_name: albion.guildbot
    image: aliart/albion.guildbot:1.0
    build:
      context: ./
      dockerfile: docker/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/connected"]
      interval: 30s
      timeout: 10s
      retries: 2
