#!/usr/bin/env bash

if  [ -f "/app/package.json" ]; then
    cd /app \
        && su  -c "npm install" guildbot \
        && su  -c "npm start" guildbot
    
else
    echo "Error: /app/package.json not found"  
fi